# Programming for Data Science and Artificial Intelligence

## 2 Numpy

### Readings: 
- [VANDER] Ch2
- https://numpy.org/doc/stable/

NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

A python list comes with overhead of determining its dynamic type and convert them back to C.  Unlike python list, Numpy is constrained to arrays that all contain the same type, thus removing that overhead.

In [1]:
import numpy as np
np.__version__

'1.19.4'

## Creation

From list

In [2]:
l = [1, 2, 3, 4]
l_numpy = np.array(l)
print("List to numpy: ", l_numpy)

List to numpy:  [1 2 3 4]


Creating using np built-in functions

In [3]:
print("1: Np zeors: ", np.zeros(10, dtype=int))
print("2: Np ones: ", np.ones((3,5), dtype=float))
print("3: Np full: ", np.full((4,2), 3.14))

#super handy
#here, we create 5 equal-distanced values from 0 to 1
print("4: Np linspace: ", np.linspace(0, 1, 5))

#we also have log space 10^1, 10^?
print("5: Np logspace: ", np.logspace(1, 2, 5))

#diag
print("6: Np diag: ", np.diag(np.arange(4)))

#identity matrix with size 3 x 3 for computing inverse of matrix
print("7: Np eye: ",np.eye(3))

#if you just want a scratch array, use empty
# values will be whatever already exists at that memory
print("8: Np empty: ", np.empty(3))

1: Np zeors:  [0 0 0 0 0 0 0 0 0 0]
2: Np ones:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3: Np full:  [[3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]]
4: Np linspace:  [0.   0.25 0.5  0.75 1.  ]
5: Np logspace:  [ 10.          17.7827941   31.6227766   56.23413252 100.        ]
6: Np diag:  [[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
7: Np eye:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
8: Np empty:  [1. 1. 1.]


Creating with data types

In [4]:
#if some is integer, some is float.  All will be upcasted to float
l = [1.3, 2, 3, 4]
l_numpy = np.array(l)
print("1: Typecasting: ", l_numpy)

#we can also expliclty define the type
l = [1, 2, 3, 4]
l_numpy_float = np.array(l, dtype='float32')
print("2: Dtype: ", l_numpy_float)

#astype, copy of the array, and cast to a specified type
#astype is a function of every numpy array, NOT np method
l_numpy_int32 = l_numpy_float.astype(int)
print("3: l_num_int32 using astype: ", l_numpy_int32)

1: Typecasting:  [1.3 2.  3.  4. ]
2: Dtype:  [1. 2. 3. 4.]
3: l_num_int32 using astype:  [1 2 3 4]


Creating multi-dimensional numpy array

In [5]:
l = [[1, 2], [3, 4]]
l_numpy = np.array(l)
print("1: Multidimensional: ", l_numpy)

#we can also leverage the list comprehension method
print("2: List comprehension: ", 
      np.array([range(i, i+3) for i in [2, 4, 6]]))

1: Multidimensional:  [[1 2]
 [3 4]]
2: List comprehension:  [[2 3 4]
 [4 5 6]
 [6 7 8]]


Creating randomized numpy arrays

In [6]:
#Return random floats in the half-open interval [0.0, 1.0)
print("1: Randomize [0, 1)", np.random.random((3,3)))  #randomize a 3x3 array between 0 and 1

#random integers in the interval [0, 10)
print("2: Random integers [0, 10)", np.random.randint(0, 10, (3, 3)))

#normal distribution with m=0 and std=1
print("3: Normal dist. with m=0 and std=1", np.random.normal(0, 1, (3, 3)))

1: Randomize [0, 1) [[0.21651616 0.66468694 0.82305512]
 [0.83835798 0.12847361 0.07126763]
 [0.11523168 0.84905677 0.40732162]]
2: Random integers [0, 10) [[8 0 4]
 [1 9 9]
 [6 2 6]]
3: Normal dist. with m=0 and std=1 [[-0.84102303  0.43400673  0.68763132]
 [ 0.97907639  0.62335478 -1.75365615]
 [ 1.40990249 -0.8359568   0.84063445]]


### ===Task===

1. Declare a list of 1 to 4 using range()

2. Continuing, create numpy array from this list, with dtype='float32'

3. Create an numpy array of size 3 by 5 using np.zeros

4. Create an numpy array of size 2 by 3 with filled value 1 / 3

5. Create a list of 500 numbers for 0 to 10

6. Create a list of number for 0.001, 0.01, 0.1, 1 using np.logspace

7. Create a diagonal matrix of list [1, 2, 3, 4]

8. Create a random array of size 4 by 5 all filled with random values between 0 and 1

9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5

10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5

11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution

12. Create an identity matrix of size 5 by 5

## Attributes

First let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [7]:
import numpy as np
np.random.seed(1) #seed for reproducibility

x1 = np.random.randint(10, size = 6) #one dimensional array
print("1D: ", x1)
x2 = np.random.randint(10, size = (3, 4)) #two 
print("2D: ", x2)
x3 = np.random.randint(10, size = (3, 4, 5)) #three
print("3D: ", x3)

1D:  [5 8 9 5 0 0]
2D:  [[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
3D:  [[[7 9 1 7 0]
  [6 9 9 7 6]
  [9 1 0 1 8]
  [8 3 9 8 7]]

 [[3 6 5 1 9]
  [3 4 8 1 4]
  [0 3 9 2 0]
  [4 9 2 7 7]]

 [[9 8 6 9 3]
  [7 7 4 5 9]
  [3 6 8 0 2]
  [7 7 9 7 3]]]


Dim

In [8]:
#observe the bracket in front to easily determine the dimension
#or simply use ndim
print(f"Dim: X1: {x1.ndim}, X2: {x2.ndim}, X3: {x3.ndim}")

Dim: X1: 1, X2: 2, X3: 3


Shape

In [9]:
#to observe the size of each dimension, use shape
#shape will be your most likely companion throughout your coding exp.
print(f"Shape: X1: {x1.shape}, X2: {x2.shape}, X3: {x3.shape}")

Shape: X1: (6,), X2: (3, 4), X3: (3, 4, 5)


Len

In [10]:
print(f"Len (but only first dim!): X1: {len(x1)}, X2: {len(x2)}, X3: {len(x3)}")

Len (but only first dim!): X1: 6, X2: 3, X3: 3


Size

In [11]:
#to get number of elements, use ize
print(f"Size: X1: {x1.size}, X2: {x2.size}, X3: {x3.size}")

Size: X1: 6, X2: 12, X3: 60


Dtypes

In [12]:
print(f"Dtype: X1: {x1.dtype}, X2: {x2.dtype}, X3: {x3.dtype}")

Dtype: X1: int64, X2: int64, X3: int64


## Indexing and Slicing

Basic indexing

In [13]:
print("1: X1: ", x1)
print("2: X1 first element: ", x1[0])
print("3: X1 first two elements: ", x1[:2])
print("4: X1 last element: ", x1[-1])
print("5: X1 last two element: ", x1[-2:])

1: X1:  [5 8 9 5 0 0]
2: X1 first element:  5
3: X1 first two elements:  [5 8]
4: X1 last element:  0
5: X1 last two element:  [0 0]


2D array access

In [14]:
print("1: X2: ", x2)
print("2: X2 default access row-wise: ", x2[0])
print("3: X2 first row, third col: ", x2[0, 2])
print("4: X2 first row, last col: ", x2[0, -1])
print("5: X2 every row, last two col: ", x2[:, -2:])
print("6: X2 reversed: ", x2[::-1, ::-1])
print("7: X2 last two rows, every even col: ", x2[-2:, 1::2])

1: X2:  [[1 7 6 9]
 [2 4 5 2]
 [4 2 4 7]]
2: X2 default access row-wise:  [1 7 6 9]
3: X2 first row, third col:  6
4: X2 first row, last col:  9
5: X2 every row, last two col:  [[6 9]
 [5 2]
 [4 7]]
6: X2 reversed:  [[7 4 2 4]
 [2 5 4 2]
 [9 6 7 1]]
7: X2 last two rows, every even col:  [[4 2]
 [2 7]]


3D array access

In [15]:
print("1: X3: ", x3)
print("2: X3 default access row-wise: ", x3[0])
print("3: X3 first sheet, third row, last col: ", x3[0, 2, -1])
print("4: X3 second sheet, first two rows, last two cols: ", x3[1, :2, -2:])
print("5: X3 second sheet, everything, everything (essentially converting to 2D - very useful): ", x3[1, :, :])
print("6: X3 second sheet, without : : ", x3[1])

1: X3:  [[[7 9 1 7 0]
  [6 9 9 7 6]
  [9 1 0 1 8]
  [8 3 9 8 7]]

 [[3 6 5 1 9]
  [3 4 8 1 4]
  [0 3 9 2 0]
  [4 9 2 7 7]]

 [[9 8 6 9 3]
  [7 7 4 5 9]
  [3 6 8 0 2]
  [7 7 9 7 3]]]
2: X3 default access row-wise:  [[7 9 1 7 0]
 [6 9 9 7 6]
 [9 1 0 1 8]
 [8 3 9 8 7]]
3: X3 first sheet, third row, last col:  8
4: X3 second sheet, first two rows, last two cols:  [[1 9]
 [1 4]]
5: X3 second sheet, everything, everything (essentially converting to 2D - very useful):  [[3 6 5 1 9]
 [3 4 8 1 4]
 [0 3 9 2 0]
 [4 9 2 7 7]]
6: X3 second sheet, without : :  [[3 6 5 1 9]
 [3 4 8 1 4]
 [0 3 9 2 0]
 [4 9 2 7 7]]


Modifying

In [16]:
print("1: X2 first row, last col before: ", x2[0, -1])
x2[0, -1] = 99.013  #remember that x2 is a int type, so it will automatically truncate decimals
print("2: X2 first row, last col after: ", x2[0, -1])

1: X2 first row, last col before:  9
2: X2 first row, last col after:  99


### ===Task===

1. Create a numpy array of size 3 by 4 with random float values between 1 to 5 but skipping 3

2. Continuing, print the shape of this array

3. Continuing, access the first row of the array

4. Continuing, access the first column of the array

5. Continuing, access the second row, and third column element

6. Continuing, access the first two columns

7. Continuing, access the  first and third columns using step

8. Continuing, print the whole matrix in reverse columns but not rows

9. Change the third row, fourth column element (i.e., the last element) to 999

### Very very important reminder - subarray are not copies!

In [17]:
some_array = np.random.randint(10, size = 6) #one dimensional array
print("1: some_array: ", some_array)

its_not_copy = some_array[1:3]
print("2: its_not_copy", its_not_copy)

its_not_copy[0] = 99

print("Some array got changed!!")
print("3: some_array: ", some_array)
print("4: its_not_copy", its_not_copy)

'''
This behavior is intended, since data scientists 
love to chop down dataset to subset when working
'''

#if we want copy, use copy()
another_array = np.random.randint(10, size = 6) #one dimensional array
print("5: another_array: ", another_array)

its_copy = another_array[1:3].copy()
print("6: its_copy", its_copy)

its_copy[0] = 99

print("7: another_array: ", another_array)
print("8: its_copy", its_copy)


1: some_array:  [0 8 7 7 1 1]
2: its_not_copy [8 7]
Some array got changed!!
3: some_array:  [ 0 99  7  7  1  1]
4: its_not_copy [99  7]
5: another_array:  [3 0 8 6 4 5]
6: its_copy [0 8]
7: another_array:  [3 0 8 6 4 5]
8: its_copy [99  8]


## Reshaping

Simple reshape

In [18]:
grid = np.arange(1, 10)
print("1:", grid)
print("2: Make sure no. of elements match!: ", grid.size == 3 * 3)
print("3: New grid: ", grid.reshape((3,3)))  #reshape take a tuple as input

1: [1 2 3 4 5 6 7 8 9]
2: Make sure no. of elements match!:  True
3: New grid:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


1d to 2d

In [19]:
X = np.array([11, 22, 33, 44, 55])
print("1: X: ", X)
print("2: X shape: ", X.shape)  #you cannot input this to scikit learn since it expects (samples, features)
X = X.reshape((X.shape[0], 1))
print("3: 1D to 2D: ", X)
print("4: X reshape: ", X.shape)

1: X:  [11 22 33 44 55]
2: X shape:  (5,)
3: 1D to 2D:  [[11]
 [22]
 [33]
 [44]
 [55]]
4: X reshape:  (5, 1)


np.newaxis

In [20]:
#another way to reshape is to use np.newaxis
# 1D array
X = np.arange(4)
print("1: X: ", X.shape)

# make it as row vector by inserting an axis along second dimension
row_vec = X[np.newaxis, :]
print("2: Row vec: ", row_vec.shape)

# make it as column vector by inserting an axis along second dimension
col_vec = X[:, np.newaxis]
print("3: Col vec: ", col_vec.shape)

1: X:  (4,)
2: Row vec:  (1, 4)
3: Col vec:  (4, 1)


Common to reshape 2d to 3d for time algorithms, such as LSTM

In [21]:
X = np.array([[11, 22],
              [33, 44],
              [55, 66]])

print("1: X: ", X)
print("2: X shape: ", X.shape)  #you cannot input this to LSTM since it expects (samples, time steps, features)

#this X can be framed as 1 sample with 3 time steps and 2 features
X = X.reshape(1, X.shape[0], 2)
print("3: 2D to 3D: ", X)
print("4: X reshape : ", X.shape)

1: X:  [[11 22]
 [33 44]
 [55 66]]
2: X shape:  (3, 2)
3: 2D to 3D:  [[[11 22]
  [33 44]
  [55 66]]]
4: X reshape :  (1, 3, 2)


Using -1 in reshape

In [22]:
# -1 in reshape allow numpy to automatically 
# determine the correct shape; super useful
X = np.array([[[ 0, 1],
               [ 2, 3]],
              [[ 4, 5],
               [ 6, 7]],
              [[ 8, 9],
               [10, 11]],
              [[12, 13],
               [14, 15]]])

print("1: X: ", X)
print("2: X shape: ", X.shape)

X = X.reshape(-1, 2)
print("3: 3D to 2D using -1: ", X)
print("4: X reshape using -1: ", X.shape)

1: X:  [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
2: X shape:  (4, 2, 2)
3: 3D to 2D using -1:  [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
4: X reshape using -1:  (8, 2)


### ===Task===

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5

2. Continuing, split the array into two numpy arrays, set the first array <code>X_train</code> to contain 70\% of the 200 rows, and contains the first 3 columns.  The second array <code>y_train</code> contains 70\% of the 200 rows but only for the last column.  Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.

3. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, )

4. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features

5. Reshape the <code>y_train</code> so that its shape is (0.7 * 200, 1) 

6. Randomly select one row of <code>X_train</code> and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>

7. Randomly select 50 contiguous rows from <code>X_train</code> and called it <code>mini_batch_X</code>

8. Write a for loop that breaks the <code>X_train</code> into 10 equal pieces without overlap, each containing 10\% of row data but all columns, and simply print their shape

9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>

10. Perform a dot product between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>

11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.

12. Calculate the following 
    $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
    For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
    $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

## Concatenation, vstack/hstack

Concatenation

In [23]:
x = np.array([[1, 2, 3], 
              [3, 4, 1]])
y = np.array([[3, 2, 1]])

print("1: x: ", x.shape, "y: ", y.shape)

#all the input arrays must have same number of shape
#except in the dimension corresponding to the axis
print("2: Row concatenation: ", np.concatenate((x, y)))  #default axis = 0 (i.e., row)

1: x:  (2, 3) y:  (1, 3)
2: Row concatenation:  [[1 2 3]
 [3 4 1]
 [3 2 1]]


Error example

In [24]:
#default axis = 1 (i.e., col).  Error because row has different dimension
#print("Column concatenation: ", np.concatenate((x, y), axis=1))  

More example

In [25]:
X = np.array([[11, 22],
              [33, 44],
              [55, 66]])

Y = np.array([[11, 22],
              [33, 44],
              [55, 66]])

print("1: X: ", X.shape, "Y: ", Y.shape)

print("2: Row concat: ", np.concatenate([X, Y]))  #default axis = 0
print("3: Col concat: ", np.concatenate([X, Y], axis=1))  #default axis = 1

1: X:  (3, 2) Y:  (3, 2)
2: Row concat:  [[11 22]
 [33 44]
 [55 66]
 [11 22]
 [33 44]
 [55 66]]
3: Col concat:  [[11 22 11 22]
 [33 44 33 44]
 [55 66 55 66]]


Concatenating multiple lists

In [26]:
Z = np.array([[11, 22],
              [33, 44],
              [55, 66]])

print("Concat multiple list: ", np.concatenate((X, Y, Z)))

#Tips: Notice sometimes I use () or [] inside concatenate, 
#they both work since concatenate expect a tuple or lists of arrays

Concat multiple list:  [[11 22]
 [33 44]
 [55 66]
 [11 22]
 [33 44]
 [55 66]
 [11 22]
 [33 44]
 [55 66]]


Vstack and hstack

In [27]:
#instead of using axis =0 or 1, we can use hstack or vstack
#as name suggests, hstack stack horizontally (axis = 1) and
#vstack stack vertically (axis = 0)
print("1: Vstack (row-wise): ", np.vstack((X, Y, Z)))
print("2: Hstack (col-wise): ", np.hstack((X, Y, Z)))

1: Vstack (row-wise):  [[11 22]
 [33 44]
 [55 66]
 [11 22]
 [33 44]
 [55 66]
 [11 22]
 [33 44]
 [55 66]]
2: Hstack (col-wise):  [[11 22 11 22 11 22]
 [33 44 33 44 33 44]
 [55 66 55 66 55 66]]


## Vectorization

Vectorization basics

In [28]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 1, 1, 5, 1])
print("a + b", a + b)

a + b [2 3 4 9 6]


Vectorization by scalars

In [29]:
print("1: 1 - a", 1 - a)
print("2: a ** 2", a ** 2)
print("3: -a + 5 / 10", (-a + 5) / 10)  #imagine apply f(x) across all values

1: 1 - a [ 0 -1 -2 -3 -4]
2: a ** 2 [ 1  4  9 16 25]
3: -a + 5 / 10 [0.4 0.3 0.2 0.1 0. ]


Vectorization using numpy built in function

In [30]:
print("1: np.add(a, b): ", np.add(a, b))
print("2: np.mod(a, 3): ", np.mod(a, 3))
#imagine this [i for i in a if a % 3 == 0]
print("3: np.min: ", np.min(a)) #return value
print("4: np.argmin: ", np.argmin(a)) #returns index
print("5: np.dot(a, b): ", np.dot(a, b))
print("6: np.abs(b): ", np.abs(b))

#you can also use other wrappers like
#np.add, np.subtract, np.negatve, np.multiply, np.divide
#np.floor_divide, np.power, np.mod, np.mean, np.var
#np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan
#np.exp - base e, np.exp2, np.power
#np.log - ln x, np.log2, np.log10

1: np.add(a, b):  [2 3 4 9 6]
2: np.mod(a, 3):  [1 2 0 1 2]
3: np.min:  1
4: np.argmin:  0
5: np.dot(a, b):  31
6: np.abs(b):  [1 1 1 5 1]


## Broadcasting

Broadcasting is actually a built-in vectorization technique when shape is different

Here are the broadcasting rules:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

A simple way to think about broadcasting is as follows:

<code>a = 5
b = np.array([1, 1, 1])  #shape with (3, )
a + b = [6, 6, 6]</code>

Actually, what broadcasting does is to stretch a to [5, 5, 5] to match the dimension of b.  As you can see, the shape of [5, 5, 5] has shape with (3, ) as well.  BTW, this duplication does not actually take place, but it is a useful mental model to think about broadcasting

Example 1

In [31]:
a = np.ones((2, 3))
print("1: A: ", a, " shape: ", a.shape)
b = np.arange(3)
print("2: B: ", b, " shape: ", b.shape)

'''
what is a + b?
First, rule 1 applies since a and b has different dimension
the smaller one is padded with 1 from left
resulting in B having shape of (1, 3) and A still has shape of (2, 3)

Now, since dimension one does not match, 1 and 2, thus the 1 will be 
stretched to become 2
resulting in B having shape of (2, 3) and A still has shape of (2, 3)

And thus the result is of shape (2, 3)
'''

print("3: A + B: ", a + b)
print("4: A + B shape: ", (a+b).shape)

1: A:  [[1. 1. 1.]
 [1. 1. 1.]]  shape:  (2, 3)
2: B:  [0 1 2]  shape:  (3,)
3: A + B:  [[1. 2. 3.]
 [1. 2. 3.]]
4: A + B shape:  (2, 3)


Example 2

In [32]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)
print("1: A: ", a, " shape: ", a.shape)
print("2: B: ", b, " shape: ", b.shape)

'''
B has fewer dimension, Rule 1 applies thus shape from (3, ) becomes (1, 3)
Now A has shape of (3, 1) and B has shape of (1, 3)
Rule 2 applies, stretching any one of match the other, thus
A has shape of (3, 3) and B has shape of (3, 3)
'''

print("3: A + B: ", a + b)
print("4: A + B shape: ", (a+b).shape)

1: A:  [[0]
 [1]
 [2]]  shape:  (3, 1)
2: B:  [0 1 2]  shape:  (3,)
3: A + B:  [[0 1 2]
 [1 2 3]
 [2 3 4]]
4: A + B shape:  (3, 3)


Example 3

In [33]:
a = np.ones((3, 2))
b = np.arange(3)
print("1: A: ", a, " shape: ", a.shape)
print("2: B: ", b, " shape: ", b.shape)

'''
By Rule 1, B has fewer dimension, thus becomes (1, 3) while A still has (3, 2)
By Rule 2, then B becomes (3, 3) while A is still (3, 2)
Since no more rule can be applied, this results in an error
'''
#error
#print("A + B: ", a + b)
#print("A + B shape: ", (a+b).shape)

#this is where reshaping comes to the rescue
#perhaps we can reshape B to (3, 1)
b = b.reshape(b.shape[0], 1)
print("3: B new: ", b)
print("4: B newshape: ", b.shape)
print("5: A + B: ", a + b)
print("6: A + B shape: ", (a+b).shape)

1: A:  [[1. 1.]
 [1. 1.]
 [1. 1.]]  shape:  (3, 2)
2: B:  [0 1 2]  shape:  (3,)
3: B new:  [[0]
 [1]
 [2]]
4: B newshape:  (3, 1)
5: A + B:  [[1. 1.]
 [2. 2.]
 [3. 3.]]
6: A + B shape:  (3, 2)


Example 4

In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3])
print("1: A: ", a, " shape: ", a.shape)
print("2: B: ", b, " shape: ", b.shape)

'''
Rule 1 cannot be applied since they have same dimension
Rule 2 cannot be applied as well since there are no ones
'''
#errors
# a + b
#in this case, we can add 1 to a or b
a = a[:, np.newaxis] 
print("3: A: ", a, " shape: ", a.shape)
print("4: B: ", b, " shape: ", b.shape)
print("5: A + B: ", a + b)

#applying newaxis to a becomes (5, 3), if b becomes (3, 5)
print("6: A + B shape: ", (a+b).shape)

1: A:  [1 2 3 4 5]  shape:  (5,)
2: B:  [5 4 3]  shape:  (3,)
3: A:  [[1]
 [2]
 [3]
 [4]
 [5]]  shape:  (5, 1)
4: B:  [5 4 3]  shape:  (3,)
5: A + B:  [[ 6  5  4]
 [ 7  6  5]
 [ 8  7  6]
 [ 9  8  7]
 [10  9  8]]
6: A + B shape:  (5, 3)


### ===Task===


1. Given a function $y = 0.5x + 1$
   - generate 1000 points from 1 to 10 and called it X
   - calculate corresponding y

2. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1

3. Create a <code>theta</code> of shape (n, 4)

4. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>

5. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

$$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

The second value 0.5 will become

exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

6. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

7. Create a variable called <code>y</code>, containing shape of <code>(X.shape[0], )</code> but with random int values from [0, 1, 2, 3]

8. Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0

9. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>

## Masking

Instead of writing if/while, we can use Boolean masks to elegantly extract desired values from numpy arrays.  You will love it!!

In [35]:
rng = np.random.RandomState(0)  #for reproducibility
x = rng.randint(10, size=(3, 4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


Examples

In [36]:
print("1: x<4: ", x<4)
print("2: All values less than 4: ", x[x<4])
print("3: All values divisible by 3: ", x[x%3==0])
print("4: All values that are nan: ", x[np.isnan(x)])

1: x<4:  [[False  True  True  True]
 [False False  True False]
 [ True False False False]]
2: All values less than 4:  [0 3 3 3 2]
3: All values divisible by 3:  [0 3 3 9 3 6]
4: All values that are nan:  []


Argwhere

In [37]:
print("Argwhere: ", np.argwhere(x<4))

Argwhere:  [[0 1]
 [0 2]
 [0 3]
 [1 2]
 [2 0]]


Np.any

In [38]:
print("1: Any value ==0? ", np.any(x==0))
print("2: Any value ==0 along axis 1?", np.any(x==0, axis=1))
print("3: Any value ==0 along axis 0?", np.any(x==0, axis=0))

1: Any value ==0?  True
2: Any value ==0 along axis 1? [ True False False]
3: Any value ==0 along axis 0? [False  True False False]


Np.all

In [39]:
#count IF ALL value is > 0
print(np.all(x>0))

False


Multiple conditions

In [40]:
#definitely multiple conditions can be done
print(np.any((x==0) & (x==2)))

False


## Fancy indexing

Instead of pass individual indices, we can pass array of indices all at once, and it will return a list of numbers

In [41]:
import random
a = np.random.randint(100, size = 10)
print(a)

[70  2 76 91 21 75  7 77 72 75]


Basic example

In [42]:
print("1: Normal indices: ", a[0], a[3], a[5])
print("2: Fancy indices: ", a[[0, 3, 5]])  #remember that the argument is a list

#error!
#print("Common mistake: ", a[0, 3, 5])

1: Normal indices:  70 91 75
2: Fancy indices:  [70 91 75]


Shape of fancy indexing

In [43]:
'''
When using fancy indexing, the shape of the 
result reflects the shape of the index arrays 
rather than the shape of the array being indexed:
'''
ix = np.array([[3, 7],
               [4, 5]])
print("Shape follow ix shape: ", a[ix])

Shape follow ix shape:  [[91 77]
 [21 75]]


Multiple dimension fancy indexing

In [44]:
X = np.arange(12).reshape((3,4))
print("1: X 2D: ", X)
row_ix = np.array([0, 1, 2])
col_ix = np.array([2, 1, 3])
print("2: X[row_ix, col_ix]: ", X[row_ix, col_ix]) #[0, 2], [1, 1], [2, 3]
print("3: X[2,  [2, 0, 1]]: ", X[2, [2, 0, 1]])
print("4: X[1:, [2, 0, 1]]: ", X[1:, [2, 0, 1]])

1: X 2D:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2: X[row_ix, col_ix]:  [ 2  5 11]
3: X[2,  [2, 0, 1]]:  [10  8  9]
4: X[1:, [2, 0, 1]]:  [[ 6  4  5]
 [10  8  9]]


Combined indexing with indexing/slicing

In [45]:
print("1: Slicing + fancy + masking: ", X[1:, [2, 0, 1]][X[1:, [2, 0, 1]]%2==0])

#if you do not like above, here probably more readable
Y = X[1:, [2, 0, 1]]
print("2: More readable way: ", Y[Y%2==0])

1: Slicing + fancy + masking:  [ 6  4 10  8]
2: More readable way:  [ 6  4 10  8]


3d

In [46]:
X = np.arange(36).reshape((3, 4, 3))
print("1: X 3D: ", X)
print("2: X 3D  X[1, [1, 0, 1], [2, 1, 1]]: ", X[1, [1, 0, 1], [2, 1, 1]])
print("3: X 3D  X[1:, [1, 0, 1], [2, 1, 1]]: ", X[1:, [1, 0, 1], [2, 1, 1]])
print("4: X 3D  X[1:, [1, 0, 1]]: ", X[1:, [1, 0, 1]])
print("5: X 3D  X[[1,0,1], [1, 0, 1],[1,0,1]]: ", X[[1,0,1], [1, 0, 1],[1,0,1]])
print("6: X 3D  X[[1,0,1], [1, 0, 1],[1,0,1]]: ", X[[1,0,1], [1, 0, 1],[1,0,1]])

1: X 3D:  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
2: X 3D  X[1, [1, 0, 1], [2, 1, 1]]:  [17 13 16]
3: X 3D  X[1:, [1, 0, 1], [2, 1, 1]]:  [[17 13 16]
 [29 25 28]]
4: X 3D  X[1:, [1, 0, 1]]:  [[[15 16 17]
  [12 13 14]
  [15 16 17]]

 [[27 28 29]
  [24 25 26]
  [27 28 29]]]
5: X 3D  X[[1,0,1], [1, 0, 1],[1,0,1]]:  [16  0 16]
6: X 3D  X[[1,0,1], [1, 0, 1],[1,0,1]]:  [16  0 16]


Modifying using fancy indexing

In [47]:
x = np.arange(10)
ix = np.array([2, 1, 8, 4])
x[ix] = 99
print("1: All ix values got change: ", x)

1: All ix values got change:  [ 0 99 99  3 99  5  6  7 99  9]


### ===Task===

1. From the above <code>yhat</code>, take only the values that are greater than 1 using masking.

2. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>  Hint: (use masking!)

3. Given <code>X_train</code> from above, randomly select three rows of data using fancy indexing.

4. Grab the data from <code>data = np.genfromtxt('resources/perceptron.csv', delimiter=',', skip_header=1)</code>
    - set X to be all columns except last
    - set y to be the last column
    - print the shape of X where its corresponding y is 0
    - print the shape of X where its corresponding y is 1
    
5. Grab the data from <code>iris = genfromtxt('resources/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
    - set iris_without_headers to all rows except the first row
    - set sepal_length to second column of iris_without_headers
    - set petal_length to fourth column of iris_without_headers
    - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5